# Generated by Django 3.1.6 on 2021-02-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bott', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='answer',
            new_name='answers',
        ),
    ]
