# Generated by Django 3.1.6 on 2021-02-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bott', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
