# Generated by Django 3.1.6 on 2021-02-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bott', '0004_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='USERDATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=44)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
