# Generated by Django 3.1.6 on 2021-02-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bott', '0007_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
